Update the-super-tiny-compiler.js
thejameskyle/the-super-tiny-compiler pull request #51
Opened 2017-01-02 05:46 UTC by gsklee

Made some modifications to make the newly-added text fit into existing paragraphs.

2017-01-02 23:03 UTC, jamiebuilds requested changes

2017-01-02 23:03 UTC, thejameskyle commented on the-super-tiny-compiler.js
> + * In order to supper that, the final form of our visitor will look like this:
this should say "support" too

2017-01-03 04:32 UTC, gsklee commented
@thejameskyle updated.

2017-01-04 17:21 UTC, jamiebuilds approved these changes

2017-01-04 17:21 UTC, merged